name: Test Docker Build

on:
  # 对PR进行测试构建，但不推送
  pull_request:
    branches:
      - main
      - master
    paths-ignore:
      - 'README.md'
      - '*.md'
      - '.gitignore'
      - 'LICENSE'

jobs:
  test-build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Test Docker build
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: false
        tags: test:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
    
    - name: Test container startup
      run: |
        # 创建测试环境变量文件
        cat > .env.test << EOF
        BASE=https://chat.z.ai
        PORT=8080
        MODEL=GLM-4.5
        TOKEN=
        ANONYMOUS_MODE=true
        THINK_TAGS_MODE=reasoning
        DEBUG=false
        EOF
        
        # 启动容器
        docker run -d --name test-container -p 8001:8001 --env-file .env.test test:latest
        
        # 等待容器启动
        sleep 10
        
        # 测试模型接口
        curl -f http://localhost:8080/v1/models || exit 1
        
        # 停止容器
        docker stop test-container
        docker rm test-container
        
        echo "✅ Docker container test passed!"
